spring.application.name=weather-mcp-server
spring.ai.mcp.server.version=1.0.0
# Transport: STDIO (default, for local clients) or SSE (for HTTP clients)
spring.ai.mcp.server.transport=STDIO

# Disable web server ? NOT needed for STDIO
spring.main.web-application-type=none

# Suppress all stdout
spring.main.banner-mode=off
spring.main.log-startup-info=false
spring.jmx.enabled=false
spring.ai.mcp.server.stdio=true
server.port=8022